(function(d,c){c="undefined"===typeof c?{}:c;c.Core={SliderManager:{}};c.Scope={workground:{},layerControlList:{},layerSettingsForm:{},slideFormCtrl:{},slidePageCtrl:{},styleEditorForm:{},styleEditorCtrl:{},layerPresetList:{},styleModeSwitcher:{},layerStylePreview:{}}})(jQuery,MPSL);
(function(d,c){c.Preloader=can.Construct({className:".mpsl-preloader",preloaderEl:d('<div class="mpsl-preloader">'),globalPreloaderEl:d(".mpsl-global-preloader"),disabled:!1,start:function(a){if(this.disabled)return!1;"undefined"===typeof a?this.globalPreloaderEl.show():a.length&&a.append(this.preloaderEl.clone())},stop:function(a){"undefined"===typeof a?this.globalPreloaderEl.hide():a.length&&a.children(this.className).remove()},disable:function(){this.disabled=!0},enable:function(){this.disabled=
!1}},{})})(jQuery,MPSL);
(function(d,c){c.MediaLibrary=can.Control.extend({defaults:{id:"mpsl-media-library",multiple:!1,describe:!1,toolbar:"select",sidebar:"settings",content:"upload",router:"browse",menu:"default",searchable:!0,filterable:!1,sortable:!1,title:"tmp Title",button:{text:"tmp Text"},library:{type:"image"},contentUserSetting:!0,syncSelection:!0}},{frame:null,workground:null,init:function(a,b){this.frame=wp.media(b);this.frame.on("open",this.proxy("onOpen"));this.frame.on("select",this.proxy("onSelect"));this.frame.on("close",
this.proxy("onClose"))},onOpen:function(){this.frame.reset()},onSelect:function(){var a=this.frame.state().get("selection").models[0].attributes,b="full",c="full";a.sizes.hasOwnProperty("thumbnail")&&(b="thumbnail");a.sizes.hasOwnProperty("full")?c="full":a.sizes.hasOwnProperty("large")?c="large":a.sizes.hasOwnProperty("medium")?c="medium":a.sizes.hasOwnProperty("thumbnail")&&(c="thumbnail");return{id:a.id,thumbnail:a.sizes[b].url,src:a.sizes[c].url,width:a.width,height:a.height}},onClose:function(){},
linkWokground:function(a){this.workground=a},click:function(){this.frame.open()}})})(jQuery,MPSL);
(function(d,c){c.AddImageML=c.MediaLibrary.extend({},{onSelect:function(){c.Preloader.start(d(".mpsl-slider-wrapper"));c.Preloader.start(d(".mpsl-layers-list-wrapper"));var a=this,b=this._super();b.options={image_id:b.id};var f=c.Workground.width,g=c.Workground.height,l;l=b.width/b.height;var h=f>=b.width||g>=b.height?1:2,f=f>=g?g/h*l:f/h;f>b.width&&(f=b.width);b.options.width=f;var m=c.ImageLayer.create(b),f=d.Deferred(),g=f.promise();d.when(g).then(function(){var f=a.workground.initLayer(d(m.getDomElement())),
g=d.extend({},c.Layer.getCentralOffset(),{width:c.Layer.makeLayoutedOption(f.element.width()),image_id:b.id,image_url:b.src});f.updatePosition(c.Layer.getCentralOffset(!0));f.extendOptions(g);f.select();f.control.select();f.control.scrollToElement();a.workground.setCurrent(f);c.Preloader.stop(d(".mpsl-slider-wrapper"));c.Preloader.stop(d(".mpsl-layers-list-wrapper"))});if(m.getScope().layer.created)f.resolve();else d(m.getDomElement()).one("MPSLLayerCreate",f.resolve)}})})(jQuery,MPSL);
(function(d,c){c.FormController("MPSL.LayerSettingsForm",{},{optionControllers:{},dependency:{},disabled_dependency:{},layerController:null,optionsContainer:"layer",resettingOptionsMode:!1,init:function(a,b){this._super(a,b);c.Scope.layerSettingsForm=this;this.hide();var f=d(".mpsl-layer-settings-tabs");f.tabs({active:f.children("ul").children("li:visible:first").index()});this.constructor.ready()},hide:function(){this.element.addClass("mpsl-hide-options");this.element.removeAttr("id")},show:function(){this.element.removeClass("mpsl-hide-options");
this.element.attr("id","mpsl-layer-settings-wrapper-"+this.layerController.layer.getType())},reinit:function(a){if("undefined"===typeof a)if(null!==c.Scope.workground.current)a=c.Scope.workground.current.control;else return!1;var b=this;this.layerController=a;this.resetOptions();a=d.extend(!0,{},c.Vars.layer.layouted_defaults,b.layerController.layer.options);a=b.layerController.layer.getCleanSingleLayoutOptions(a);d.each(a,function(a,c){"order"!==a&&b.optionControllers.hasOwnProperty(a)&&(b.optionControllers[a].setValue(c,
!0),b.showDependencedOptions(a))});this.showAllDependencies();this.layerController.layer.isNew&&(this.layerController.layer.setOptions(this.getOptionsList()),this.layerController.layer.isNew=!1);this.show()},resetOptions:function(){this.resettingOptionsMode=!0;var a=this,b=this.layerController.layer.cleanOptions(c.Vars.layer.defaults,!0);d.each(b,function(b,c){a.optionControllers.hasOwnProperty(b)&&a.optionControllers[b].setValue(c,!0)});this.showAllDependencies();this.resettingOptionsMode=!1},setOptions:function(a,
b){b="undefined"!==typeof b?b:!1;var c=this;d.isPlainObject(a)&&d.each(a,function(a,b){c.optionControllers.hasOwnProperty(a)&&(c.optionControllers[a].setValue(b,!0),c.showDependencedOptions(a))});b?this.layerController.layer.setOptions(this.getOptionsList()):this.render()},isResettingOptionsMode:function(){return this.resettingOptionsMode},setType:function(a){this.type=a},render:function(){this.verifyOptions()&&this.layerController.setOptions(this.getOptionsList())}})})(jQuery,MPSL);
(function(d,c){c.FormController("MPSL.StyleEditorForm",{},{optionControllers:{},dependency:{},disabled_dependency:{},preset:null,optionsContainer:"preset",styleModeSwitcher:{},preview:{},presetList:{},styleEditor:{},allowStyleControl:{},styleMode:"",defaultStyleMode:"style",hoverStyleClass:"mpsl-style-editor-hover-style",privateSelectedClass:"mpsl-style-editor-private-selected",resettingOptionsMode:!1,init:function(a,b){this._super(a,b);c.Scope.styleEditorForm=this;this.hide();this.allowStyleControl=
this.getOption("allow_style");this.styleMode=this.defaultStyleMode;this.styleModeSwitcher=new c.StyleEditorModeSwitcher(d("#mpsl-style-mode-switcher"));this.preview=new c.LayerStylePreview(d("#mpsl-style-editor-preview-area"));can.bind.call(this.styleModeSwitcher,"switch",this.proxy("styleModeChanged"));can.bind.call(c.Scope.layerPresetList.element,"presetControlSelect",this.proxy("presetControlSelected"));this.constructor.ready()},hide:function(){this.element.addClass("mpsl-hide-options")},show:function(){this.element.removeClass("mpsl-hide-options")},
reinit:function(a){this.preset=a;this.resetOptions();var b=d.extend(!0,{},c.Vars.preset.defaults,this.preset.options);d.each(b[this.styleMode],this.proxy(function(b,c){if(this.optionControllers.hasOwnProperty(b)){var d=this.optionControllers[b].setValue(c,!0);this.optionControllers[b].isAdjustment()&&!d.hasBeenSet&&a.setOption(b,d.value,this.styleMode);this.showDependencedOptions(b)}}));this.showAllDependencies();this.show()},resetOptions:function(){this.resettingOptionsMode=!0;var a=this;d.each(c.Vars.preset.defaults[this.styleMode],
function(b,c){a.optionControllers.hasOwnProperty(b)&&a.optionControllers[b].setValue(c,!0)});this.showAllDependencies();this.resettingOptionsMode=!1},setOptions:function(a,b){b="undefined"!==typeof b?b:!1;var c=this;d.isPlainObject(a)&&d.each(a,function(a,b){c.optionControllers.hasOwnProperty(a)&&(c.optionControllers[a].setValue(b,!0),c.showDependencedOptions(a))});b?this.preset.setOptions(c.getOptionsList()):this.render()},render:function(){if(this.verifyOptions()){var a=this.getOptionsList();this.preset.setOptions(a)}},
styleModeChanged:function(a,b){this.setStyleMode(b);"style"===b?(this.element.removeClass(this.hoverStyleClass),this.allowStyleControl.disable()):(this.element.addClass(this.hoverStyleClass),this.allowStyleControl.enable());var f=this.presetList.getSelected();f&&(f.getType()!==c.LayerPreset.DEFAULT&&this.reinit(f),f.render())},presetControlSelected:function(a,b){b.getType()===c.LayerPreset.PRIVATE?this.element.addClass(this.privateSelectedClass):this.element.removeClass(this.privateSelectedClass);
b.getType()!==c.LayerPreset.DEFAULT?this.reinit(b):this.hide()},getStyleMode:function(){return this.styleMode},setStyleMode:function(a){this.styleMode=-1<d.inArray(a,["style","hover"])?a:this.defaultStyleMode},resetStyleMode:function(){this.styleModeSwitcher.setMode(this.defaultStyleMode)},linkPresetList:function(a){this.presetList=a},linkStyleEditor:function(a){this.styleEditor=a},isResettingOptionsMode:function(){return this.resettingOptionsMode}})})(jQuery,MPSL);
(function(d,c){c.FormController("MPSL.SlideFormController",{},{workground:null,options:{},dependency:{},disabled_dependency:{},init:function(a,b){this._super(a,b);c.Scope.slideFormCtrl=this;var f=d("#mpsl-slide-settings-tabs");f.tabs({active:f.children("ul").children("li:visible:first").index(),activate:function(a,b){c.CodeMirrorControl.refreshEditors(b.newPanel)}});this.constructor.ready()},linkWorkground:function(a){this.workground=a},render:function(a){c.Preloader.start(d(".mpsl-slider-wrapper"));
var b={general:{},backgrounds:{}};a="undefined"!==typeof a?a:this.getOptionsList();a.hasOwnProperty("bg_color_type")&&("color"===a.bg_color_type&&a.hasOwnProperty("bg_color")&&a.bg_color.length&&(b.backgrounds.color={},b.backgrounds.color.color=a.bg_color),"gradient"===a.bg_color_type&&(a.hasOwnProperty("bg_grad_color_1")&&a.bg_grad_color_1.length||a.hasOwnProperty("bg_grad_color_2")&&a.bg_grad_color_2.length)&&(b.backgrounds.gradient={},b.backgrounds.gradient.colorInitial=a.hasOwnProperty("bg_grad_color_1")&&
a.bg_grad_color_1.length?a.bg_grad_color_1:"transparent",b.backgrounds.gradient.colorFinal=a.hasOwnProperty("bg_grad_color_2")&&a.bg_grad_color_2.length?a.bg_grad_color_2:"transparent",a.hasOwnProperty("bg_grad_angle")&&(b.backgrounds.gradient.position=(a.bg_grad_angle.length?a.bg_grad_angle:"0")+"deg")),a.hasOwnProperty("bg_image_type")&&(a.hasOwnProperty("bg_internal_image_url")&&a.bg_internal_image_url.length||a.hasOwnProperty("bg_image_url")&&a.bg_image_url.length)&&(b.backgrounds.image={},"library"===
a.bg_image_type&&""!==a.bg_internal_image_url&&(b.backgrounds.image.src=a.bg_internal_image_url),"external"===a.bg_image_type&&""!==a.bg_image_url&&(b.backgrounds.image.src=a.bg_image_url),a.hasOwnProperty("bg_position")&&(b.backgrounds.image.position=a.bg_position),a.hasOwnProperty("bg_position_x")&&(b.backgrounds.image.positionX=a.bg_position_x),a.hasOwnProperty("bg_position_y")&&(b.backgrounds.image.positionY=a.bg_position_y),a.hasOwnProperty("bg_repeat")&&(b.backgrounds.image.repeat=a.bg_repeat),
a.hasOwnProperty("bg_fit")&&(b.backgrounds.image.fit=a.bg_fit),a.hasOwnProperty("bg_fit_x")&&(b.backgrounds.image.fitX=a.bg_fit_x),a.hasOwnProperty("bg_fit_y")&&(b.backgrounds.image.fitY=a.bg_fit_y)),a.hasOwnProperty("slide_classes")&&(b.general.classes=d.trim(a.slide_classes)),a.hasOwnProperty("slide_id")&&(b.general.id=d.trim(a.slide_id)));this.workground.slideApi.setOptions(b);this.workground.updateSlideBg();c.Preloader.stop(d(".mpsl-slider-wrapper"))}})})(jQuery,MPSL);
(function(d,c){c.SlidePageController=can.Control.extend({},{slideSettingsController:null,styleEditorController:null,presetList:null,workground:null,layout:null,sliderPreviewWrapper:null,sliderPreviewIframe:null,previewForm:null,optionsInput:null,idInput:null,typeInput:null,nonceInput:null,preloader:null,resBtns:null,resolutionWrapper:null,init:function(a,b){c.Scope.slidePageCtrl=this;this.workground=new c.Workground("#mpsl-workground",{});this.layout=new c.Layout("#mpsl-change-layout",{});this.slideSettingsController=
new c.SlideFormController(".mpsl_options_wrapper");this.slideSettingsController.linkWorkground(this.workground);this.styleEditorController=new c.StyleEditorController(d("#mpsl-style-editor-modal"));this.styleEditorController.linkWorkground(this.workground);this.sliderPreviewWrapper=d(".mpsl-slider-preview");this.preloader=this.sliderPreviewWrapper.find(".mpsl-preloader");this.sliderPreviewIframe=this.sliderPreviewWrapper.find("iframe");this.desktopIcon=this.sliderPreviewWrapper.find(".desktop");this.resolutionWrapper=
this.sliderPreviewWrapper.find(".mpsl-resolution-buttons-wrapper");this.footerMessageWrapper=this.sliderPreviewWrapper.find(".mpsl-slider-preview-footer-message");var f=this,g=c.Vars.menu_url,g=c.Functions.addParamToUrl(g,"view","preview"),g=c.Functions.addParamToUrl(g,"slider_id",c.Vars.page.slider_id),g=c.Functions.addParamToUrl(g,"slide_id",c.Vars.page.id),g=c.Functions.addParamToUrl(g,"type","slide");this.sliderPreviewWrapper.dialog({resizable:!1,draggable:!1,autoOpen:!1,modal:!0,width:d(window).width()-
100,height:d(window).height()-100,title:c.Vars.lang.preview_dialog_title,closeText:"",dialogClass:"mpsl-preview-dialog",close:function(){(f.sliderPreviewIframe[0].contentDocument||f.sliderPreviewIframe[0].contentWindow.document).documentElement.innerHTML=""},beforeClose:function(){d("body").css("overflow","inherit");f.footerMessageWrapper.addClass("hidden")},open:function(){f.footerMessageWrapper.removeClass("hidden");d("body").css("overflow","hidden");f.preloader.show();f.sliderPreviewIframe.attr("src",
g);f.sliderPreviewIframe.width("100%");f.desktopIcon.siblings().removeClass("active");f.desktopIcon.addClass("active")},create:function(){f.resolutionWrapper.removeClass("hidden")}});this.resBtns=[{type:"desktop",resolution:"100%"},{type:"tablet",resolution:"768px"},{type:"mobile",resolution:"480px"}];this.resBtns.forEach(function(a){d("."+a.type).on("click",function(){f.sliderPreviewIframe.width(a.resolution);d(this).siblings().removeClass("active");d(this).addClass("active");(f.sliderPreviewIframe[0].contentWindow||
f.sliderPreviewIframe[0].contentDocument)._mpslResizePreview()})});this.sliderPreviewIframe.on("load",function(){f.preloader.hide()})},disableBtns:function(){this.element.find("#save_slide, #delete_slide").attr("disabled","disabled")},enableBtns:function(){this.element.find("#save_slide, #delete_slide").removeAttr("disabled","disabled")},"#save_slide, #slider_preview click":function(a,b){var f="slider_preview"===d(a).attr("id");f||this.disableBtns();var g=this,l=c.Vars.page.id,h=this.slideSettingsController.getFormData(),
m=this.workground.getLayersData(),n=this.styleEditorController.getPresetsData(),k=c.LayerPresetList.getLastId(),p=c.LayerPresetList.getLastPrivateId(),h={action:"mpsl_update_slide",nonce:c.Vars.nonces.update_slide,options:JSON.stringify(h),layers:JSON.stringify(m),presets:JSON.stringify(n),last_preset_id:k,last_private_preset_id:p,preview:f};l&&(h.id=l);d.ajax({type:"POST",url:c.Vars.ajax_url,data:h,success:function(a){f?g.sliderPreviewWrapper.dialog("open"):(g.enableBtns(),a.hasOwnProperty("result")&&
c.Functions.showMessage(c.Vars.lang.slide_updated,c.Functions.MSG_SUCCESS_TYPE))},error:function(a){console.log(a.responseText);a=d.parseJSON(a.responseText);a.debug?console.log(a.message):c.Functions.showMessage(a.message,c.Functions.MSG_ERROR_TYPE);g.enableBtns()},dataType:"JSON"})},"#delete_slide click":function(a){this.disableBtns();a=c.Vars.page.id;if(0==confirm(c.Vars.lang.slide_want_delete_single.replace("%d",a)))return this.enableBtns(),!0;var b={action:"mpsl_delete_slide",nonce:c.Vars.nonces.delete_slide};
a&&(b.id=a);d.ajax({type:"POST",url:c.Vars.ajax_url,data:b,success:function(a){deleteBtn.removeAttr("disabled");c.Functions.showMessage(c.Vars.lang.slide_deleted,c.Functions.MSG_SUCCESS_TYPE);a=c.Vars.menu_url;a=c.Functions.addParamToUrl(a,"view","slides");a=c.Functions.addParamToUrl(a,"id",c.Vars.page.slider_id);window.location.href=a},error:function(a){a=d.parseJSON(a.responseText);a.debug?console.log(a.message):c.Functions.showMessage(a.message,c.Functions.MSG_ERROR_TYPE);self.enableBtns()},dataType:"JSON"})},
"#create_slide click":function(a){var b=this;this.disableBtns();d.ajax({type:"POST",url:c.Vars.ajax_url,data:{action:"mpsl_create_slide",nonce:c.Vars.nonces.create_slide,slider_id:c.Vars.page.slider_id},success:function(a){a.hasOwnProperty("result")?(c.Functions.showMessage(c.Vars.lang.slide_created,c.Functions.MSG_SUCCESS_TYPE),window.location.href=c.Vars.menu_url+"&view=slide&id="+a.id):(c.Functions.showMessage(c.Vars.lang.slider_created_error,c.Functions.MSG_ERROR_TYPE),b.enableBtns())},error:function(a){a=
d.parseJSON(a.responseText);a.debug?console.log(a.message):c.Functions.showMessage(a.message,c.Functions.MSG_ERROR_TYPE);b.enableBtns()},dataType:"JSON"})}})})(jQuery,MPSL);
(function(d,c){c.StyleEditorController=can.Control.extend({},{styleSettings:{},presetList:{},workground:null,editorElement:null,editorWrapper:null,editorTabs:null,editorTabsContent:null,previewEl:null,linkedLayerControl:null,dialog:null,tabs:null,init:function(a,b){c.Scope.styleEditorCtrl=this;this.styleSettings=new c.StyleEditorForm(d(".mpsl-style-editor-settings-wrapper"),{showErrorType:"internal"});this.styleSettings.linkStyleEditor(this);this.presetList=new c.LayerPresetList("#mpsl-layer-preset-list-child-wrapper");
this.presetList.linkStyleSettings(this.styleSettings);this.presetList.linkStyleEditor(this);this.styleSettings.linkPresetList(this.presetList);this.dialog=null;this.editorElement=d("#mpsl-style-editor-modal");this.editorWrapper=d("#mpsl-style-editor-wrapper");this.presetListChildWrapper=d("#mpsl-layer-preset-list-child-wrapper");this.editorTabs=this.editorElement.find("#mpsl-style-editor-settings-wrapper");this.editorContentEl=this.editorElement.find(".mpsl-style-editor-content");this.editorFooterEl=
this.editorElement.find(".mpsl-style-editor-footer");this.previewEl=d("#mpsl-style-editor-preview-area");this.switcherEl=d("#mpsl-style-mode-switcher");this.linkedLayerControl=null;this.initEditor()},initEditor:function(){var a=this;this.editorElement.dialog({resizable:!1,draggable:!1,autoOpen:!1,modal:!0,appendTo:".mpsl-wrapper",width:1E3,height:d(window).height()-85,title:c.Vars.lang.style_editor_dialog_title,closeText:"",dialogClass:"mpsl-style-editor-dialog",position:{my:"center",at:"center",
of:window},beforeClose:function(){d("body").css("overflow","inherit")},close:function(){var b=a.presetList.getByName("private");b&&a.linkedLayerControl.helpers.private_styles.setValue(b.getData());a.presetList.unselect();a.styleSettings.resetStyleMode()},open:function(){d("body").css("overflow","hidden");a.fixDialog();var b=setTimeout(function(){a.fixDialog();clearTimeout(b)},1E3);a.styleSettings.resetStyleMode();var f=a.linkedLayerControl.getValue();a.styleSettings.preview.reset();a.loadPrivateOptions();
a.presetList.select(f,!0);c.CodeMirrorControl.refreshEditors(a.editorTabs.find(".ui-tabs-panel").eq(a.editorTabs.tabs("option","active")))},create:function(){var b=d(this).parent(".ui-dialog");b.parent(".mpsl-wrapper").length||b.appendTo(".mpsl-wrapper");a.dialog=d(this).data("ui-dialog");b=a.dialog.uiDialogTitlebar.find(".ui-dialog-title");b.addClass("mpsl-se-title-left");b.after(d('<span class="ui-dialog-title mpsl-se-title-right">'+c.Vars.lang.style_editor_dialog_presets_title+"</span>"));a.editorTabs.tabs({create:function(b,
c){a.tabs=d(this).data("ui-tabs");a.editorTabsContent=a.editorTabs.find(".ui-tabs-panel.ui-widget-content");d(window).on("resize",a.proxy("onWindowResize"))},activate:function(a,b){c.CodeMirrorControl.refreshEditors(b.newPanel)}});a.createPresetList();can.trigger(a.element,"create",[a])}})},fixDialog:function(){var a=d(window).height(),b=a-85,a=a-185;this.editorElement.dialog("option","position",{my:"center",at:"center",of:window});this.editorElement.dialog("option","height",0<b?b:0);this.editorContentEl.css("height",
0<a?a:0);var a=this.editorWrapper.outerHeight(!0),c=this.editorFooterEl.outerHeight(!0),b=a-this.previewEl.outerHeight(!0)-this.switcherEl.outerHeight(!0)-this.tabs.tablist.outerHeight(!0)-c-3,a=a-c-3;this.editorTabsContent.height(0<b?b:0);this.presetListChildWrapper.height(0<a?a:0)},loadPrivateOptions:function(){var a=this.linkedLayerControl.helpers.private_styles.getValue(),b=this.presetList.getByName("private");b&&b.setOptions(can.isEmptyObject(a)?c.LayerPreset.getDefaultsCopy():a,!0,!0)},createPresetList:function(){var a=
this;this.presetList.add("private",c.LayerPreset.getDefaultsCopy(c.Vars.lang.layer_preset_private_name),c.LayerPreset.PRIVATE);d.each(c.Vars.preset.list,function(b){a.presetList.add(b,this)});d.each(c.Vars.preset.default_list,function(b){a.presetList.add(b,this,c.LayerPreset.DEFAULT)})},onWindowResize:function(){this.editorElement.dialog("isOpen")&&this.fixDialog()},"#mpsl-save-as-layer-preset click":function(){var a=this.presetList.getSelected();a?(a=prompt(c.Vars.lang.layer_preset_enter_name,a.getLabel()),
null!=a&&(a=this.presetList.duplicate(a))&&a.select()):c.Functions.showMessage(c.Vars.lang.layer_preset_not_selected,c.Functions.MSG_INFO_TYPE)},"#mpsl-create-layer-preset click":function(){var a=prompt(c.Vars.lang.layer_preset_enter_name,"");null!=a&&(a||(a=c.Vars.lang.layer_preset_default_name),(a=this.presetList.addNew(a))&&a.select())},"#mpsl-apply-layer-preset click":function(){var a=this.presetList.getSelected();a&&(this.linkedLayerControl.setValue(a.getName()),this.dialog.close(),can.trigger(this.presetList.element,
"presetApply",[a]))},linkWorkground:function(a){this.workground=a},getPresetsData:function(){return this.presetList.getData()},linkControl:function(a){this.linkedLayerControl=a},disableBtns:function(){this.element.find("#save_slide, #delete_slide").attr("disabled","disabled")},enableBtns:function(){this.element.find("#save_slide, #delete_slide").removeAttr("disabled","disabled")}})})(jQuery,MPSL);
(function(d,c){c.Workground=can.Control.extend({defaults:{},width:null,height:null,halfWidth:null,halfHeight:null},{layers:[],current:null,layerControls:null,sliderWrapper:null,sliderBgWrapper:null,sliderContainer:null,sliderEl:null,slide:null,slideControl:null,slideBg:null,addButtons:null,deleteButtons:null,duplicateButton:null,slideApi:null,$guidesWrapper:null,$guideV:null,$guideH:null,loaded:null,slideBorder:null,scrollbarWidth:null,init:function(a,b){c.Scope.workground=this;var f=this;this.layerControls=
new c.LayerControls(".mpsl-layers-list-child-wrapper");this.layerControls.linkWorkground(this);this.sliderWrapper=a.children(".mpsl-slider-wrapper");this.sliderContainer=this.sliderWrapper.children(".motoslider_wrapper");this.addButtons=a.find(".mpsl-layer-control-panel .mpsl-add-layer");this.deleteButtons=a.find('.mpsl-layer-control-panel [class*="mpsl-delete-"]');this.dropdownLayerListWrap=a.find(".mpsl-layer-control-panel .mpsl-dropdown-layer-list-wrapper");this.dropdownLayerListButton=a.find(".mpsl-layer-control-panel .mpsl-dropdown-layer-list");
this.duplicateButton=a.find(".mpsl-duplicate-layer");this.slideBorder=d(".mpsl-slide-border");this.loaded=!1;this.scrollbarWidth=c.Functions.getScrollbarWidth();this.initControls();var g=d("#mpsl-core-css");g.length&&d("#mpsl-preset-styles-wrapper").insertAfter(g);if(this.sliderContainer.length)this.sliderContainer.one("MPSliderLoad",function(){c.Core.SliderManager=MPSLManager.getSliderManager(f.sliderContainer[0]);f.sliderBgWrapper=f.sliderWrapper.children(".mpsl-slide-bg-wrapper");f.sliderEl=f.sliderContainer.children(".ms_wrapper");
f.slide=f.sliderEl.find(".ms_current_slide");f.slideApi=c.Core.SliderManager.getSlide(f.slide[0]);f.slideBg=f.slide.children(".ms_slide_wrapper");f.$guidesWrapper=f.sliderWrapper.children(".mpsl-guides");f.$guideV=f.$guidesWrapper.children("#mpsl-guide-v");f.$guideH=f.$guidesWrapper.children("#mpsl-guide-h");f.resizeWorkground(f.sliderEl.outerWidth(),f.sliderEl.outerHeight());f.sliderBgWrapper.append(f.slideBg.children().clone());f.initLayers();f.addButtons.removeAttr("disabled");f.deleteButtons.filter(".mpsl-delete-all-layers").removeAttr("disabled");
f.loaded=!0;can.trigger(f,"load");c.Preloader.stop()});else c.Preloader.stop()},resizeWorkground:function(a,b){c.Workground.width=a;c.Workground.height=b;c.Workground.halfWidth=c.Workground.width/2;c.Workground.halfHeight=c.Workground.height/2;this.sliderContainer.css("width",a);this.sliderBgWrapper.css({"min-width":a,height:b});this.$guidesWrapper.css({"min-width":a,height:b});this.slideBorder.css("width",a);this.sliderWrapper.css("max-height",b+this.scrollbarWidth)},initControls:function(){var a=
this.addButtons.filter('[data-type="image"]');(new c.AddImageML(a,{id:"mpsl-add-image-ml",title:"New Image",button:{text:c.Vars.layer.options.image_id.select_label}})).linkWokground(this)},updateSlideBg:function(){this.sliderBgWrapper.html(this.slide.children(".ms_slide_wrapper").children().clone())},duplicateLayer:function(a){var b={options:d.extend(!0,{},a.options)},f={};switch(a.getType()){case "image":b=d.extend({},b,{width:a.options.width,image_id:a.options.image_id,image_url:a.options.image_url});
f.width=a.getLayoutOption("width");break;case "html":f.width=a.getLayoutOption("html_width");break;case "youtube":case "vimeo":case "video":f.width=a.getLayoutOption("video_width"),f.height=a.getLayoutOption("video_height")}var g="";a.options.hasOwnProperty("private_preset_class")&&a.options.private_preset_class&&(g=a.options.private_preset_class,delete b.options.private_preset_class);var l=c.Layer.duplicate(a,f);a.isType(["html","button"])&&l.setFontOptions(a.getLayoutFontOptions());d.when(this.initNewLayer(l,
b)).then(function(a){if(g){var b=d(l.getDomElement()).find("."+g);b.length&&(b.attr("class",b.attr("class").replace(g,a.options.private_preset_class)),c.Scope.layerStylePreview.update(d.extend(!0,{},a.options.private_styles),a.options.private_preset_class,!0))}})},initNewLayer:function(a,b){var f=d.Deferred(),g=f.promise();if(a){var l=this,h=d.Deferred(),m=h.promise();if(a.getScope().layer.created)h.resolve();else d(a.getDomElement()).one("MPSLLayerCreate",h.resolve);d.when(m).then(function(){var g=
l.initLayer(d(a.getDomElement())),k=d.extend(!0,{},b.options,c.Layer.getCentralOffset());g.updatePosition(c.Layer.getCentralOffset(!0));g.extendOptions(k);g.select();g.control.select();g.control.scrollToElement();l.current=g;c.Preloader.stop(d(".mpsl-slider-wrapper"));f.resolve(g)})}else f.reject();return g},'.mpsl-layer-control-panel .mpsl-add-layer:not([data-type="image"]) click':function(a){c.Preloader.start(d(".mpsl-slider-wrapper"));var b={options:{}},f=null;switch(a.attr("data-type")){case "html":b.options=
{type:"html",text:c.Vars.layer.defaults.text,html_width:c.Layer.makeLayoutedOption(c.Vars.layer.defaults.html_width),html_style:""};f=c.HtmlLayer.create(b);break;case "button":b.options={button_text:c.Vars.layer.defaults.button_text,button_link:c.Vars.layer.defaults.button_link,button_target:c.Vars.layer.defaults.button_target,button_style:""};f=c.ButtonLayer.create(b);break;case "video":b.options={video_type:"youtube",youtube_src:"https://www.youtube.com/watch?v=t0jFJmTDqno",youtube_thumbnail:"https://i.ytimg.com/vi/t0jFJmTDqno/maxresdefault.jpg",
video_preview_image:"",video_youtube_hide_controls:!1,video_width:c.Layer.makeLayoutedOption(c.Vars.layer.defaults.video_width),video_height:c.Layer.makeLayoutedOption(c.Vars.layer.defaults.video_height)},f=c.VideoLayer.create(b)}this.initNewLayer(f,b)},".mpsl-layer-control-panel .mpsl-duplicate-layer click":function(){c.Preloader.start(d(".mpsl-slider-wrapper"));this.duplicateLayer(this.current)},".mpsl-layer-control-panel .mpsl-delete-layer click":function(){this.remove()},".mpsl-layer-control-panel .mpsl-delete-all-layers click":function(){confirm(c.Vars.lang.layer_want_delete_all)&&
(this.layerControls.removeAll(),this.removeAll(),this.onUnselect())},".mpsl-layer-control-panel .mpsl-dropdown-layer-list click":function(){this.dropdownLayerListWrap.toggleClass("mpsl-dropdown-open");this.dropdownLayerListButton.toggleClass("active");this.layerControls.initStyles()},remove:function(){this.current&&(this.layerControls.remove(this.current.control),this.layers.splice(this.current.getOrder(),1),this.resetOrder(),this.current.api.remove(),this.current=null);this.onUnselect()},removeAll:function(){d.each(this.layers,
function(){this.api.remove()});this.layers=[];this.current=null},initLayers:function(){var a=this;this.slide.find(".ms_layers_wrapper > .layers").each(function(){a.initLayer(d(this),!1)})},initLayer:function(a,b){var f=c.Core.SliderManager.getLayer(a[0]),d=f.getType(),l=f.getOrder(),h=null,m={order:l};if("undefined"!==typeof d&&d){switch(d){case "html":m.type=d;h=new c.HtmlLayer(a,m,b);break;case "button":m.type=d;h=new c.ButtonLayer(a,m,b);break;case "image":m.type=d;h=new c.ImageLayer(a,m,b);break;
case "video":m.type="video";m.video_type="html";h=new c.VideoLayer(a,m,b);break;case "youtube":m.type="video";m.video_type="youtube";h=new c.VideoLayer(a,m,b);break;case "vimeo":m.type="video",m.video_type="vimeo",h=new c.VideoLayer(a,m,b)}h.linkWorkground(this);h.linkAPI(f);this.layerControls.add(h,l,d+" "+l,{});this.layers.push(h)}return h},setCurrent:function(a){this.current=a},getCurrent:function(){return this.current},getLayersData:function(){return this.layerControls.getData()},onSelect:function(a){this.current=
a;this.deleteButtons.filter(".mpsl-delete-layer").removeAttr("disabled");this.duplicateButton.removeAttr("disabled")},onUnselect:function(){this.deleteButtons.filter(".mpsl-delete-layer").attr("disabled","disabled");this.duplicateButton.attr("disabled","disabled");this.current=null},resetOrder:function(){d.each(this.layers,function(a,b){b.setOrder(a)})},reorder:function(){var a=this;d.each(this.layerControls.controls,function(b,c){a.layers[b]=c.layer;c.layer.setOrder(b)})},".mpsl-slider-wrapper mousedown":function(){d.each(this.layers,
function(){this.unselect()});this.onUnselect()},repaintLayers:function(){d.each(this.layers,function(a,b){b.repaintLayer()})}})})(jQuery,MPSL);
(function(d,c){c.LayerControl=can.Control.extend({defaults:{}},{layer:null,order:null,layersControls:{},init:function(a,b){},destroy:function(){this.unselect();can.Control.prototype.destroy.call(this)},click:function(a){this.layer.select();this.select()},select:function(){this.element.hasClass("layer-control-selected")||(this.element.siblings().removeClass("layer-control-selected"),this.element.addClass("layer-control-selected"),c.Scope.layerSettingsForm.reinit(this))},unselect:function(){this.element.hasClass("layer-control-selected")&&
(this.element.removeClass("layer-control-selected"),c.Scope.layerSettingsForm.hide())},linkLayer:function(a){this.layer=a},setOrder:function(a){this.order=a},getOrder:function(){return this.order},getData:function(){return this.layer.options},setOptions:function(a){a.hasOwnProperty("type")&&"video"===a.type&&this.updateLabel("html"===a.video_type?"video":a.video_type);this.layer.setOptions(a);this.layer.render()},updateLabel:function(a){this.layersControls.updateLayerLabel(this.getOrder(),a)},linkLayerControls:function(a){this.layersControls=
a},scrollToElement:function(){this.layersControls.element.animate({scrollTop:this.layersControls.element.scrollTop()+this.element.position().top-this.layersControls.element.position().top-this.layersControls.element.height()/2+this.element.height()/2},100)}})})(jQuery,MPSL);
(function(d,c){c.LayerControls=can.Control.extend({defaults:{}},{controls:[],listContainer:null,workground:null,formSettings:{},stylesInited:!1,init:function(a,b){c.Scope.layerControlList=this;this.listContainer=a.find(".mpsl-layers-table > tbody");this.makeSortable();this.formSettings=new c.LayerSettingsForm(d(".mpsl-layer-settings-wrapper"),{showErrorType:"internal"})},initStyles:function(){this.stylesInited||(this.element.css("max-height",250-d(".mpsl-layers-table-head").outerHeight()),this.stylesInited=
!0)},makeSortable:function(){var a=this;this.listContainer.sortable({handle:".mpsl-layer-drag-handle",scroll:!0,helper:function(a,c){c.children().each(function(){d(this).width(d(this).width())});return c},start:function(a,c){var g=d(c.item).control();g.select();g.layer.select()},update:function(){d(a.listContainer.children("tr").get().reverse()).each(function(b,c){a.controls[b]=d(c).control();a.controls[b].setOrder(b)});a.workground.reorder()}})},add:function(a,b,f,g){g=d("<tr>");var l=d('<td class="mpsl-layer-drag-handle">').text("");
f=d('<td class="mpsl-layer-label">').text(f);g.append(l,f);this.listContainer.prepend(g);f=new c.LayerControl(g);f.setOrder(b);f.linkLayer(a);f.linkLayerControls(this);a.linkControl(f);this.controls.push(f)},linkWorkground:function(a){this.workground=a},remove:function(a){this.controls.splice(a.getOrder(),1);this.resetOrder();a.element.remove()},removeAll:function(){d.each(this.controls,function(){this.element.remove()});this.controls=[]},resetOrder:function(){d.each(this.controls,function(a,b){b.setOrder(a)})},
getData:function(){var a=[];d.each(this.controls,function(b,c){a[c.getOrder()]=c.getData()});return a},updateLayerLabel:function(a,b,c){a=d(this.listContainer.children("tr").get().reverse()[a]).find(".mpsl-layer-label");var g=a.text().split(" ");g[0]=b;"undefined"!==typeof c&&(g[1]=c);b=g.join(" ");a.text(b)}})})(jQuery,MPSL);
(function(d,c){c.Layer=can.Control.extend({defaults:{},whiteSpaceClassPrefix:c.Vars.layer.white_space_class_prefix,create:function(){},duplicate:function(a,b){return c.Core.SliderManager.duplicateLayer(a.api,b)},getCentralOffset:function(a){var b=c.Vars.layer.defaults.hor_align,f=c.Vars.layer.defaults.vert_align,g={align:{hor:b,vert:f},hor_align:b,vert_align:f,offset_x:c.Vars.layer.defaults.offset_x,offset_y:c.Vars.layer.defaults.offset_y};("undefined"===typeof a?0:a)||d.each(g,function(a,b){g[a]=
c.Layer.makeLayoutedOption(b)});return g},prepareOptionsForApi:function(a){a=d.extend(!0,{},a);a.hasOwnProperty("classes")||(a.classes="");a.classes=c.Vars.preset.layer_class+" "+a.classes;return a},getByLayout:function(a){return c.Layer.isLayoutFormat(a)?a[c.Layout.getLayout()]:a},isLayoutFormat:function(a){return"object"===typeof a&&a.hasOwnProperty("desktop")},makeLayoutedOption:function(a,b,f){f="undefined"===typeof f?!0:f;var d={};if("undefined"===typeof b||!b){for(var l in c.Vars.layout.list)d[l]=
f?null:a;d[c.Vars.layout["default"]]=a}d[c.Layout.getLayout()]=a;return d}},{order:null,options:{},prevOptions:{},control:null,object:null,presetOwnerObject:null,handle:null,container:null,api:null,type:null,workground:null,resizableOptions:{},draggableOptions:{},droppableOptions:{},resizable:!1,isNew:!1,shiftPressed:!1,onChangeData:{},storage:{youtubeThumbnails:{},vimeoThumbnails:{}},needReinitFlag:!1,MIN_DISTANCE:10,setup:function(a,b,f){this.isNew=f="undefined"!==typeof f?f:!0;this._super(a,b);
this.options={};this.order=b.order;f||"undefined"===typeof c.Vars.layer.list[this.order]?d.extend(!0,this.options,c.Vars.layer.layouted_defaults,b):d.extend(!0,this.options,c.Vars.layer.list[this.order],b);this.options.private_styles=d.extend(!0,{},c.Vars.preset.defaults,this.options.private_styles);this.cleanOptions();this.options.hasOwnProperty("private_preset_class")&&"undefined"!==typeof this.options.private_preset_class&&this.options.private_preset_class||(this.options.private_preset_class=c.LayerPresetList.privateClassPrefix+
c.LayerPresetList.getNextPrivateId());d.extend(!0,this.prevOptions,this.options);this.presetOwnerObject=this.object=a.children();this.container=a.closest(".ms_wrapper")},resetObject:function(){this.presetOwnerObject=this.object=this.element.children(".ms_layer")},init:function(a,b){this.api=c.Core.SliderManager.getLayer(this.element[0]);this.type=this.api.getType();this.prepare();this.preventEvents();this.initWidgets();this.initEvents();this.element.on("MPSLLayerChange",this.proxy("onLayerChange"))},
reinit:function(){this.resetObject();this.api=c.Core.SliderManager.getLayer(this.element[0]);this.type=this.api.getType();this.object.addClass("mpsl-layer-child-fix");this.reprepare();this.preventEvents();this.object.on("MPSLLayerChange",this.proxy("onLayerChange"));this.needReinitFlag=!1},needReinit:function(){this.needReinitFlag=!0},isNeedReinit:function(){return this.needReinitFlag},prepare:function(){var a,b={top:this.object.position().top};"right"===this.getLayoutOption("hor_align")?(a="right",
this.setLeftAuto()):a="left";b[a]=parseFloat(this.object.css(a));this.element.css(b);this.addFixClasses()},addFixClasses:function(){this.element.addClass("mpsl-layer-fix");this.object.addClass("mpsl-layer-child-fix")},addCustomFixClasses:function(){},reprepare:function(){this.addFixClasses();this.addCustomFixClasses()},initWidgets:function(){this.addHelpers();this.resizable&&this.makeResizable();this.makeDraggable()},addHelpers:function(){this.element.append(d("<div>",{"class":"mpsl-layer-handle",
tabindex:1}));this.handle=this.element.children(".mpsl-layer-handle")},computeGuidesForElement:function(a,b,c,g){null!=a&&(a=d(a),b=a.offset(),c=a.outerWidth()-1,g=a.outerHeight()-1);return[{type:"h",left:b.left,top:b.top},{type:"h",left:b.left,top:b.top+g},{type:"v",left:b.left,top:b.top},{type:"v",left:b.left+c,top:b.top},{type:"h",left:b.left,top:b.top+g/2},{type:"v",left:b.left+c/2,top:b.top}]},makeDraggable:function(){var a=this,b,f,g,l,h,m,n,k={scroll:!1,grid:[1,1],start:function(b){a.isType("html")&&
""===a.getLayoutOption("html_width")&&a.element.addClass("mpsl-editor-wh-auto");f=a.element.width();var k=a.element.siblings(".layers");h=d.map(k,a.proxy("computeGuidesForElement"));g=b.originalEvent.offsetX;l=b.originalEvent.offsetY;m=c.Scope.workground.sliderContainer.offset();n=c.Scope.workground.sliderWrapper.offset();n.left-=c.Scope.workground.sliderWrapper.scrollLeft()},stop:function(f,d){a.isType("html")&&""===a.getLayoutOption("html_width")&&a.element.removeClass("mpsl-editor-wh-auto").css({width:"",
height:""});b=a.getOffsets();a.workground.layerControls.formSettings.setOptions(b,!0);c.Scope.workground.$guideV.hide();c.Scope.workground.$guideH.hide()},drag:function(b,k){var q={top:{dist:a.MIN_DISTANCE+1},left:{dist:a.MIN_DISTANCE+1}},u=a.element,s={top:b.originalEvent.pageY-l,left:b.originalEvent.pageX-g},r=u.outerWidth()-1,u=u.outerHeight()-1,t=a.computeGuidesForElement(null,s,r,u);d.each(h,function(a,b){d.each(t,function(a,c){if(b.type==c.type){var f="h"==b.type?"top":"left",d=Math.abs(c[f]-
b[f]);d<q[f].dist&&(q[f].dist=d,q[f].offset=c[f]-s[f],q[f].guide=b)}})});q.top.dist<=a.MIN_DISTANCE?(c.Scope.workground.$guideH.css("top",q.top.guide.top-m.top).show(),k.position.top=q.top.guide.top-q.top.offset-m.top):(c.Scope.workground.$guideH.hide(),k.position.top=s.top-m.top);q.left.dist<=a.MIN_DISTANCE?(c.Scope.workground.$guideV.css("left",q.left.guide.left-n.left).show(),k.position.left=q.left.guide.left-q.left.offset-m.left):(c.Scope.workground.$guideV.hide(),k.position.left=s.left-m.left);
"right"===a.getLayoutOption("hor_align")&&a.element.css("right",Math.round(c.Workground.width-k.position.left-f))}};this.mergeWidgetOprions(k,this.draggableOptions);this.element.draggable(k);this.afterMakeDraggable()},makeResizable:function(){var a=this,b={handles:"n, e, s, w, se, sw, ne, nw",minWidth:1,minHeight:1,start:function(b,c){a.resizeStart(d(this),b,c)},resize:function(){d(this).height(a.object.outerHeight(!0))},stop:function(b,c){a.resizeStop(d(this),b,c)}};this.mergeWidgetOprions(b,this.resizableOptions);
this.element.resizable(b);this.afterMakeResizable()},afterMakeResizable:function(){},afterMakeDraggable:function(){},resizeStart:function(a,b,c){b=this.object.outerWidth(!0)-this.object.width()+1;this.isType("image")&&(b+=this.image.outerWidth(!0)-this.image.width());a.resizable("option","minWidth",b)},resizeStop:function(a,b,c){a=this.getObjectWidth();b=this.getOffsets();this.isType("html")?b.html_width=a:b.width=a;this.workground.layerControls.formSettings.setOptions(b,!0);this.updateSize(a)},mergeWidgetOprions:function(a,
b){d.each(b,function(b,c){a[b]=c});return a},getObjectWidth:function(){return this.isType("image")?this.image.width():this.object.width()},mouseenter:function(a){this.element.hasClass("layer-selected")||(this.object.addClass(c.Vars.preset.layer_hover_class),this.presetOwnerObject.addClass(c.Vars.preset.layer_hover_class))},":not(.layer-selected) mouseleave":function(){this.element.hasClass("layer-selected")||(this.object.removeClass(c.Vars.preset.layer_hover_class),this.presetOwnerObject.removeClass(c.Vars.preset.layer_hover_class))},
mousedown:function(a,b){b.stopPropagation();this.object.removeClass(c.Vars.preset.layer_hover_class);this.presetOwnerObject.removeClass(c.Vars.preset.layer_hover_class);this.select();this.control.select();this.control.scrollToElement()},select:function(){this.workground.current&&this.workground.current.handle.blur();this.focusWithoutScrolling();this.element.hasClass("layer-selected")||(this.element.siblings(".layers").removeClass("layer-selected"),this.element.addClass("layer-selected"),this.workground.onSelect(this),
can.trigger(this.workground,"layerSelect"))},unselect:function(){this.workground.current&&this.workground.current.handle.blur();this.element.hasClass("layer-selected")&&(this.element.removeClass("layer-selected"),this.control.unselect())},linkControl:function(a){this.control=a},getOrder:function(){return this.order},setOrder:function(a){this.order=a;this.element.css("z-index",100+a)},getType:function(){return this.type},preventEvents:function(){this.object.off("click")},onLayerChange:function(a,b){this.isNeedReinit()&&
this.reinit();this.isType(["html","image"])&&this.updateSize(this.onChangeData.width);this.isType(["video","vimeo","youtube"])&&this.updateSize(this.onChangeData.width,this.onChangeData.height);this.updatePosition(this.onChangeData.offset);this.onChangeData.widthChanged&&this.workground.layerControls.formSettings.setOptions(this.getOffsets(),!0);c.Preloader.stop(d(".mpsl-slider-wrapper"))},isType:function(a){a="string"===typeof a?[a]:a;return-1<d.inArray(this.type,a)},getLayoutFontOptions:function(){var a=
{};d.each(c.Vars.layout.style_options,this.proxy(function(b,c){a[c]=this.getLayoutOption(c)}));return a},repaintLayer:function(){this.isType(["html","button"])&&(this.api.setFontOptions(this.getLayoutFontOptions()),this.isType("html")&&this.api.setOption("whiteSpace",this.getLayoutOption("white-space")),this.isType("button")&&this.clearWH());var a="",b="";switch(this.getType()){case "html":this.options.hasOwnProperty("html_width")&&(a=this.getLayoutOption("html_width"));this.updateSize(a);break;case "image":this.options.hasOwnProperty("width")&&
(a=this.getLayoutOption("width"));this.updateSize(a);break;case "video":case "youtube":case "vimeo":this.options.hasOwnProperty("video_width")&&(a=this.getLayoutOption("video_width")),this.options.hasOwnProperty("video_height")&&(b=this.getLayoutOption("video_height")),this.updateSize(a,b)}this.updatePosition({hor_align:this.getLayoutOption("hor_align"),vert_align:this.getLayoutOption("vert_align"),offset_x:this.getLayoutOption("offset_x"),offset_y:this.getLayoutOption("offset_y")})},linkAPI:function(a){this.api=
a},linkWorkground:function(a){this.workground=a},getOption:function(a){return this.options[a]},getLayoutOption:function(a,b){b="undefined"===typeof b?"current":b;var f;f="object"===typeof b?b[a]:"current"===b?this.options[a]:this.prevOptions[a];var d=c.Scope.workground.layerControls.formSettings.optionControllers;d.hasOwnProperty(a)&&d[a].isLayoutDependent&&this.constructor.isLayoutFormat(f)&&(f=null!==f[c.Layout.getLayout()]?f[c.Layout.getLayout()]:this.getDependOnValue(f));return f},getDependOnValue:function(a,
b){"undefined"===typeof b&&(b=c.Vars.layout.list[c.Layout.getLayout()].depend_on);var f=a[b];if(null===f){var d=c.Vars.layout.list[b].depend_on;d!==b&&(f=this.getDependOnValue(a,d))}return f},setOptionValue:function(a,b){var f=c.Scope.workground.layerControls.formSettings.optionControllers;f.hasOwnProperty(a)&&f[a].isLayoutDependent?(f=c.Layout.getLayout(),this.options[a][f]=b):this.options[a]=b},getSingleLayoutOptions:function(a){var b="current";"undefined"===typeof a?a=this.options:b=a;var c=this,
g={};d.each(a,function(a,d){g[a]=c.getLayoutOption(a,b)});return g},cleanOptions:function(a,b){a="undefined"===typeof a?this.options:a;("undefined"===typeof b?0:b)&&(a=d.extend(!0,{},a));d.each(a,function(b){if(c.Vars.layer.options.hasOwnProperty(b)){var g=c.Vars.layer.options[b].layer_type;"string"===typeof g&&"all"==g||-1<d.inArray(a.type,g)||delete a[b]}});return a},getCleanSingleLayoutOptions:function(a,b){"undefined"===typeof a&&(a=this.options,b=!0);a=("undefined"===typeof b?0:b)?d.extend(!0,
{},a):a;this.cleanOptions(a);return a=this.getSingleLayoutOptions(a)},setOptions:function(a){a.order=this.order;d.extend(!0,this.prevOptions,this.options);var b=this;d.each(a,function(a,c){b.setOptionValue(a,c)})},extendOptions:function(a){d.extend(!0,this.options,a)},render:function(){var a=this;c.Preloader.start(d(".mpsl-slider-wrapper"));var b={},f=null,g=null,l=!1;this.options.hasOwnProperty("width")&&this.object.width()!=parseInt(this.getLayoutOption("width"))&&(l=!0);this.options.hasOwnProperty("html_width")&&
""!==this.getLayoutOption("html_width")&&this.object.width()!=parseInt(this.getLayoutOption("html_width"))&&(l=!0);if(this.options.hasOwnProperty("video_width")&&this.object.width()!=parseInt(this.getLayoutOption("video_width"))||this.options.hasOwnProperty("video_height")&&this.object.height()!=parseInt(this.getLayoutOption("video_height")))l=!0;var h=a.getLayoutOption("type"),m="video"===h?a.getLayoutOption("video_type"):"",n="classes";"image"===h&&d.trim(a.getLayoutOption("image_link"))&&(n="linkClasses");
var k={},p={},v=[];d.each(this.getSingleLayoutOptions(),function(l,h){switch(l){case "vert_align":case "hor_align":case "offset_x":case "offset_y":b[l]=h;break;case "text":a.getLayoutOption("text","prev")!==h&&(k.content=h);break;case "html_style":k.hasOwnProperty("classes")&&k.classes.length?k.classes+=" "+h:k.classes=h;break;case "html_width":f=h;break;case "button_text":k.title=h;break;case "button_style":k.hasOwnProperty("classes")&&k.classes.length?k.classes+=" "+h:k.classes=h;break;case "button_macros":k.button_macros=
h;break;case "preset":var s="private"===h?a.getLayoutOption("private_preset_class"):h;k.hasOwnProperty(n)&&k[n].length?k[n]+=" "+s:k[n]=s;break;case "width":f=h;break;case "image_url":k.src=h;break;case "image_link":k.link=h;break;case "video_type":"youtube"===h&&(k.type="youtube");"vimeo"===h&&(k.type="vimeo");"html"===h&&(k.type="video");a.isType(k.type)||a.needReinit();break;case "video_src_mp4":if("html"!==m)break;k.hasOwnProperty("sources")||(k.sources={});k.sources.mp4=d.trim(h);break;case "video_src_webm":if("html"!==
m)break;k.hasOwnProperty("sources")||(k.sources={});k.sources.webm=d.trim(h);break;case "video_src_ogg":if("html"!==m)break;k.hasOwnProperty("sources")||(k.sources={});k.sources.ogg=d.trim(h);break;case "youtube_src":if("youtube"!==m)break;k.src=h;break;case "vimeo_src":if("vimeo"!==m)break;k.src=h;break;case "video_width":f=h;break;case "video_height":g=h;break;case "video_html_hide_controls":k.controls=!h;break;case "video_youtube_hide_controls":k.controls=!h;break;case "video_preview_image":if(d.trim(h).length)k.poster=
d.trim(h);else switch(m){case "html":k.poster="";break;case "youtube":var r=d.trim(a.getLayoutOption("youtube_src"));if(a.storage.youtubeThumbnails.hasOwnProperty(r))k.poster=a.storage.youtubeThumbnails[r];else{var t=d.Deferred();v.push(t.promise());d.ajax({type:"GET",url:c.Vars.ajax_url,cache:!0,data:{action:"mpsl_get_youtube_thumbnail",nonce:c.Vars.nonces.get_youtube_thumbnail,src:a.getLayoutOption("youtube_src")},success:function(b){k.poster=b.result;a.storage.youtubeThumbnails[r]=b.result;t.resolve()},
error:function(a){a=d.parseJSON(a.responseText);t.reject(a.message)},dataType:"JSON"})}break;case "vimeo":if(r=d.trim(a.getLayoutOption("vimeo_src")),a.storage.vimeoThumbnails.hasOwnProperty(r))k.poster=a.storage.vimeoThumbnails[r];else{var w=d.Deferred();v.push(w.promise());d.ajax({type:"GET",url:c.Vars.ajax_url,data:{action:"mpsl_get_vimeo_thumbnail",nonce:c.Vars.nonces.get_vimeo_thumbnail,src:a.getLayoutOption("vimeo_src")},success:function(b){k.poster=b.result;a.storage.vimeoThumbnails[r]=b.result;
w.resolve()},error:function(a){a=d.parseJSON(a.responseText);w.reject(a.message)},dataType:"JSON"})}}break;case "classes":k.hasOwnProperty("classes")&&k.classes.length?k.classes+=" "+h:k.classes=h;k.classes=d.trim(k.classes);break;case "image_link_classes":k.hasOwnProperty("linkClasses")&&k.linkClasses.length?k.linkClasses+=" "+h:k.linkClasses=h;k.linkClasses=d.trim(k.linkClasses);break;case "white-space":a.getLayoutOption("white-space","prev")!==h&&(k.whiteSpace=h);break;default:-1<d.inArray(l,c.Vars.layout.style_options)&&
(p[l]=h)}});k[n]=c.Vars.preset.layer_class+" "+k[n];this.onChangeData={widthChanged:l,offset:b,width:f,height:g};this.isType(["button"])&&this.clearWH();d.when.apply(d,v).then(function(){a.isType(["html","button"])&&a.api.setFontOptions(p);a.api.setOptions(k)},function(a){c.Functions.showMessage(a,c.Functions.MSG_ERROR_TYPE)})},getOffsets:function(a,b,f){var d=c.Workground.halfHeight,l=c.Workground.halfWidth;a="undefined"===typeof a?this.element.position().left:a;b="undefined"===typeof b?this.element.position().top:
b;var h="undefined"===typeof f?this.element.outerWidth(!0):f,m=this.element.outerHeight(!0),n=m/2,k=h/2,p={hor_align:this.getLayoutOption("hor_align"),vert_align:this.getLayoutOption("vert_align")};"left"===this.getLayoutOption("hor_align")?p.offset_x=a:"center"===this.getLayoutOption("hor_align")?(this.isType("html")&&""===this.getLayoutOption("html_width")&&"normal"===this.getLayoutOption("white-space")&&(this.addZeroLeftPos(),h="undefined"===typeof f?this.element.outerWidth(!0):f,k=h/2,this.removeZeroLeftPos()),
p.offset_x=a+k-l):p.offset_x=c.Workground.width-a-h;"top"===this.getLayoutOption("vert_align")?p.offset_y=b:"middle"===this.getLayoutOption("vert_align")?p.offset_y=b+n-d:p.offset_y=c.Workground.height-b-m;p.offset_x=Math.round(p.offset_x);p.offset_y=Math.round(p.offset_y);return p},updatePosition:function(a){a.offset_x=parseInt(a.offset_x);a.offset_y=parseInt(a.offset_y);var b=c.Workground.halfHeight,f=c.Workground.halfWidth,d=this.element.outerWidth(!0),d=d/2,l={left:"",right:""};"left"===a.hor_align?
l.left=a.offset_x:"center"===a.hor_align?(this.isType("html")&&""===this.getLayoutOption("html_width")&&"normal"===this.getLayoutOption("white-space")&&(this.addZeroLeftPos(),d=this.element.outerWidth(!0),d/=2,this.removeZeroLeftPos()),l.left=f-d+a.offset_x):l.right=a.offset_x;"right"===a.hor_align?this.setLeftAuto():this.setLeftCustom();this.element.css(l);f=this.element.outerHeight(!0);l={};l.top="top"===a.vert_align?a.offset_y:"middle"===a.vert_align?b-f/2+a.offset_y:c.Workground.height-f-a.offset_y;
this.element.css(l)},addZeroLeftPos:function(){this.element.addClass("mpsl-editor-layer-pos")},removeZeroLeftPos:function(){this.element.removeClass("mpsl-editor-layer-pos")},setLeftAuto:function(){this.element.addClass("mpsl-pos-left-auto")},setLeftCustom:function(){this.element.removeClass("mpsl-pos-left-auto")},initEvents:function(){var a=this,b,c,g,l,h;this.handle.on("keydown",function(m){b=parseInt(m.keyCode);16==b&&(a.shiftPressed=!0);if(-1<d.inArray(b,[46,8]))m.preventDefault(),a.workground.remove();
else if(-1<d.inArray(b,[37,38,39,40])){m.preventDefault();"right"===a.getLayoutOption("align").hor?(g="right",l=-1):(g="left",l=1);c={top:parseInt(a.element.css("top"))};c[g]=parseInt(a.element.css(g));h=1;a.shiftPressed&&(l*=10,h*=10);switch(b){case 37:a.element.css(g,c[g]-l);break;case 39:a.element.css(g,c[g]+l);break;case 38:h*=-1;case 40:a.element.css("top",c.top+h)}a.workground.layerControls.formSettings.setOptions(a.getOffsets(),!0)}});this.handle.on("keyup",function(c){b=parseInt(c.keyCode);
16==b&&(a.shiftPressed=!1)})},focusWithoutScrolling:function(){var a=window.scrollX,b=window.scrollY;this.handle.focus();window.scrollTo(a,b);this.workground.sliderWrapper.scrollTop(0)},clearWH:function(){this.element.css({width:"",height:""})}})})(jQuery,MPSL);
(function(d,c){c.HtmlLayer=c.Layer.extend({defaults:{},prepareOptionsForApi:function(a){a=this._super(a);var b={position:{},classes:""};a.hasOwnProperty("type")&&(b.type=a.type);a.hasOwnProperty("text")&&(b.content=a.text);a.hasOwnProperty("classes")&&(b.classes=a.classes);a.hasOwnProperty("html_style")&&(b.classes+=" "+a.html_style);a.hasOwnProperty("html_width")&&(b.width=c.Layer.getByLayout(a.html_width));a.hasOwnProperty("vertical_position")&&("top"===a.vertical_position&&a.hasOwnProperty("top")&&
(b.position.offsetTop=a.top),"bottom"===a.vertical_position&&a.hasOwnProperty("bottom")&&(b.position.offsetBottom=a.bottom));a.hasOwnProperty("horizontal_position")&&("left"===a.horizontal_position&&a.hasOwnProperty("left")&&(b.position.offsetLeft=a.left),"right"===a.horizontal_position&&a.hasOwnProperty("right")&&(b.position.offsetRight=a.right));return b},create:function(a){a=c.HtmlLayer.prepareOptionsForApi(a.options);return c.Core.SliderManager.createLayer("html",a)}},{resizable:!0,resizableOptions:{handles:"e, w",
grid:[1,1]},options:{},setup:function(a,b,c){this._super(a,b,c)},init:function(a,b){this._super(a,b)},prepare:function(){this._super();if(this.options.hasOwnProperty("html_width")&&""!==this.getLayoutOption("html_width")){var a=this.object[0].getBoundingClientRect();this.element.css("width",Math.round(a.width));this.object.css("width","")}},updateSize:function(a){if(""===a)this.element.css({width:"",height:""});else if(null!==a){a=parseFloat(a);var b=this.object.outerWidth(!0)-this.object.width();
this.element.css({width:a+b+"px",height:""})}},resizeStart:function(a,b,c){this._super(a,b,c)}})})(jQuery,MPSL);
(function(d,c){c.ButtonLayer=c.Layer.extend({defaults:{},prepareOptionsForApi:function(a){a=this._super(a);var b={position:{},classes:""};a.hasOwnProperty("type")&&(b.type=a.type);a.hasOwnProperty("button_text")&&(b.title=a.button_text);a.hasOwnProperty("button_link")&&(b.link=a.button_link);a.hasOwnProperty("button_target")&&(b.target=a.button_target);a.hasOwnProperty("classes")&&(b.classes=a.classes);a.hasOwnProperty("button_style")&&(b.classes+=" "+a.button_style);a.hasOwnProperty("vertical_position")&&
("top"===a.vertical_position&&a.hasOwnProperty("top")&&(b.position.offsetTop=a.top),"bottom"===a.vertical_position&&a.hasOwnProperty("bottom")&&(b.position.offsetBottom=a.bottom));a.hasOwnProperty("horizontal_position")&&("left"===a.horizontal_position&&a.hasOwnProperty("left")&&(b.position.offsetLeft=a.left),"right"===a.horizontal_position&&a.hasOwnProperty("right")&&(b.position.offsetRight=a.right));return b},create:function(a){a=c.ButtonLayer.prepareOptionsForApi(a.options);return c.Core.SliderManager.createLayer("button",
a)}},{resizable:!1,init:function(a,b){this._super(a,b)},preventEvents:function(){this._super();this.object.attr("href","javascript:void(0)").attr("disabled","disabled")},afterMakeResizable:function(){this.element.resizable("disable").removeClass("ui-state-disabled")}})})(jQuery,MPSL);
(function(d,c){c.ImageLayer=c.Layer.extend({prepareOptionsForApi:function(a){a=this._super(a);var b={position:{},classes:""};a.hasOwnProperty("classes")&&(b.classes=a.classes);a.hasOwnProperty("type")&&(b.type=a.type);a.hasOwnProperty("width")&&(b.width=a.width);a.hasOwnProperty("vertical_position")&&("top"===a.vertical_position&&a.hasOwnProperty("top")&&(b.position.offsetTop=a.top),"bottom"===a.vertical_position&&a.hasOwnProperty("bottom")&&(b.position.offsetBottom=a.bottom));a.hasOwnProperty("horizontal_position")&&
("left"===a.horizontal_position&&a.hasOwnProperty("left")&&(b.position.offsetLeft=a.left),"right"===a.horizontal_position&&a.hasOwnProperty("right")&&(b.position.offsetRight=a.right));return b},create:function(a){var b=c.ImageLayer.prepareOptionsForApi(a.options);b.src=a.src;return c.Core.SliderManager.createLayer("image",b)}},{image:null,resizable:!0,resizableOptions:{aspectRatio:!0,handles:"se, sw, ne, nw",grid:[1,1]},init:function(a,b){this.presetOwnerObject=this.image=this.object.children();this._super(a,
b)},prepare:function(){this._super();var a=this.object[0].getBoundingClientRect();this.element.css("width",Math.round(a.width));this.addCustomFixClasses()},addCustomFixClasses:function(){this.object.addClass("mpsl-image-layer-child-fix")},updateSize:function(a){if(null!==a){a=parseFloat(a);var b=this.object.outerWidth(!0)-this.object.width(),b=b+(this.image.outerWidth(!0)-this.image.width());this.element.css("width",a+b+"px");this.element.css("height","")}this.object.css("width","100%")}})})(jQuery,
MPSL);
(function(d,c){c.VideoLayer=c.Layer.extend({defaults:{},prepareOptionsForApi:function(a){a=this._super(a);var b={position:{},classes:""};if(a.hasOwnProperty("video_type"))switch(a.video_type){case "youtube":b.type="youtube",a.hasOwnProperty("youtube_src")&&(b.src=a.youtube_src),a.hasOwnProperty("video_youtube_hide_controls")&&(b.controls=!a.video_youtube_hide_controls),a.hasOwnProperty("video_preview_image")&&a.video_preview_length?b.poster=a.video_preview_image:a.hasOwnProperty("youtube_thumbnail")?b.poster=
a.youtube_thumbnail:b.poster=""}a.hasOwnProperty("video_width")&&(b.width=c.Layer.getByLayout(a.video_width));a.hasOwnProperty("video_height")&&(b.height=c.Layer.getByLayout(a.video_height));a.hasOwnProperty("classes")&&(b.classes=a.classes);a.hasOwnProperty("vertical_position")&&("top"===c.Layer.getByLayout(a.vertical_position)&&a.hasOwnProperty("top")&&(b.position.offsetTop=a.top),"bottom"===c.Layer.getByLayout(a.vertical_position)&&a.hasOwnProperty("bottom")&&(b.position.offsetBottom=a.bottom));
a.hasOwnProperty("horizontal_position")&&("left"===c.Layer.getByLayout(a.horizontal_position)&&a.hasOwnProperty("left")&&(b.position.offsetLeft=a.left),"right"===c.Layer.getByLayout(a.horizontal_position)&&a.hasOwnProperty("right")&&(b.position.offsetRight=a.right));return b},create:function(a){a=c.VideoLayer.prepareOptionsForApi(a.options);return c.Core.SliderManager.createLayer(a.type,a)}},{resizable:!0,resizableOptions:{grid:[1,1]},prepare:function(){this._super();var a=this.object[0].getBoundingClientRect();
this.element.css({width:Math.round(a.width),height:Math.round(a.height)});this.addCustomFixClasses()},addCustomFixClasses:function(){this.object.addClass("mpsl-video-layer-child-fix")},resizeStop:function(a,b,c){a=this.object.width();b=this.object.height();c=this.getOffsets();c.video_width=a;c.video_height=b;this.workground.layerControls.formSettings.setOptions(c,!0);this.updateSize(a,b)},resize:function(a,b,c){a.children("video, iframe").width(c.size.width).height(c.size.height)},updateSize:function(a,
b){var c;null!==a&&(a=parseFloat(a),c=this.object.outerWidth(!0)-this.object.width(),this.element.css("width",a+c+"px"));null!==b&&(b=parseFloat(b),c=this.object.outerHeight(!0)-this.object.height(),this.element.css("height",b+c+"px"));this.object.css("width","100%");this.object.css("height","100%")}})})(jQuery,MPSL);
(function(d,c){c.LayerPresetList=can.Control.extend({defaults:{},classPrefix:c.Vars.preset.class_prefix,privateClassPrefix:c.Vars.preset.private_class_prefix,getLastId:function(){return c.Vars.preset.last_id},getNextId:function(){this.incLastId();return c.LayerPresetList.getLastId()},incLastId:function(){c.Vars.preset.last_id++},getLastPrivateId:function(){return c.Vars.preset.last_private_id},getNextPrivateId:function(){c.LayerPresetList.incLastPrivateId();return c.LayerPresetList.getLastPrivateId()},
incLastPrivateId:function(){c.Vars.preset.last_private_id++}},{listContainer:null,workground:null,styleSettings:{},styleEditor:{},init:function(a,b){c.Scope.layerPresetList=this;this.listContainer=a.find(".mpsl-layer-presets-table > tbody");can.bind.call(a,"presetSelect",this.proxy("onPresetSelect"))},onPresetSelect:function(a,b){b&&b.getType()===c.LayerPreset.PRIVATE&&(this.styleEditor.loadPrivateOptions(),b.select(!0))},add:function(a,b,f){f="undefined"===typeof f?c.LayerPreset.CUSTOM:f;var g=d("<tr>").attr("data-name",
a);f===c.LayerPreset.PRIVATE?g.addClass("mpsl-layer-preset-private"):f===c.LayerPreset.DEFAULT&&g.addClass("mpsl-layer-preset-default");var l=d("<td>").addClass("mpsl-layer-preset-label").text(b.settings.label),h=d("<td>").attr("title",c.Vars.lang["delete"]).text("");-1<d.inArray(f,[c.LayerPreset.PRIVATE,c.LayerPreset.DEFAULT])?h.addClass("mpsl-layer-preset-label"):h.addClass("mpsl-layer-preset-remove-handle");g.append(l,h);f===c.LayerPreset.CUSTOM?this.listContainer.children(".mpsl-layer-preset-private, :not(.mpsl-layer-preset-default)").eq(-1).after(g):
this.listContainer.append(g);g=new c.LayerPreset(g,b,{name:a,type:f});g.linkPresetList(this);can.trigger(this.element,"presetAdd",{name:a,label:b.settings.label,preset:g,isPrivate:f===c.LayerPreset.PRIVATE});return g},addNew:function(a){var b=c.LayerPresetList.classPrefix+c.LayerPresetList.getNextId();return this.add(b,c.LayerPreset.getDefaultsCopy(a))},duplicate:function(a,b){b="undefined"===typeof b?this.getSelected():b;if(!b)return!1;var d=b.getOptions({settings:{label:a}},!0),g=c.LayerPresetList.classPrefix+
c.LayerPresetList.getNextId();return this.add(g,d)},select:function(a,b){if("undefined"===typeof a)return!1;b="undefined"===typeof b?!1:b;"string"===typeof a&&(a=this.getByName(a?a:"private"));a||(a=this.getByName("private"));return a?(a.select(b),a.getName()):!1},unselect:function(a){a="undefined"===typeof a?this.getSelected():a;return(a="string"===typeof a&&a?this.getByName(a):a)?(a.unselect(),!0):!1},getSelected:function(){return this.listContainer.children(".layer-preset-control-selected").length?
this.listContainer.children(".layer-preset-control-selected").control():!1},getByName:function(a,b){b="undefined"===typeof b?!1:b;var c=this.listContainer.children('[data-name="'+a+'"]');return c.length?b?c:c.control():!1},linkStyleEditor:function(a){this.styleEditor=a},linkStyleSettings:function(a){this.styleSettings=a},remove:function(a){a.remove()},getData:function(){var a={},b;this.listContainer.children("tr").each(function(){(b=d(this).control())&&-1===d.inArray(b.getType(),[c.LayerPreset.PRIVATE,
c.LayerPreset.DEFAULT])&&(a[b.getName()]=b.getData())});return a},getStyleMode:function(){return this.styleSettings.getStyleMode()}})})(jQuery,MPSL);
(function(d,c){c.LayerPreset=can.Control.extend({CUSTOM:0,PRIVATE:1,DEFAULT:2,defaults:{},getDefaultsCopy:function(a){var b=d.extend(!0,{},c.Vars.preset.defaults);"undefined"!==typeof a&&(b.settings.label=a);return b},getFontWeightsByFont:function(a){return a?c.Vars.preset.font_list[a].variants:this.getDefaultFontWeights()},getDefaultFontWeights:function(){return c.Vars.preset.default_font_weight_list}},{type:null,name:null,label:null,lableEl:null,removeHandle:null,presetList:{},setup:function(a,
b,f){this._super(a,b);this.name=f.name;this.type=f.type;this.lableEl=a.children(".mpsl-layer-preset-label");c.Functions.disableSelection(this.lableEl);d.extend(!0,this.options,b)},destroy:function(){this.unselect();can.Control.prototype.destroy.call(this)},"> .mpsl-layer-preset-label click":function(){this.select()},"> .mpsl-layer-preset-label dblclick":function(a,b){if(-1<d.inArray(this.type,[c.LayerPreset.PRIVATE,c.LayerPreset.DEFAULT]))b.preventDefault();else{var f=prompt(c.Vars.lang.layer_preset_rename,
this.getLabel());null!=f&&f&&this.updateLabel(f)}},"> .mpsl-layer-preset-remove-handle click":function(){if(-1<d.inArray(this.type,[c.LayerPreset.PRIVATE,c.LayerPreset.DEFAULT]))e.preventDefault();else if(confirm(c.Vars.lang.layer_preset_delete.replace("%s",this.getLabel()))){var a=null;this.isSelected()&&(this.presetList.styleSettings.preview.reset(),a=this.presetList.getByName("private"));this.presetList.styleSettings.preview.removeStyles(this.name);var b=this.getName();this.element.remove();can.trigger(this.presetList.element,
"presetRemove",{name:b});a&&a.select()}},select:function(a){if(("undefined"===typeof a?0:a)||!this.isSelected())this.element.siblings().removeClass("layer-preset-control-selected"),this.element.addClass("layer-preset-control-selected"),this.render(),can.trigger(this.presetList.element,"presetControlSelect",[this])},unselect:function(){this.isSelected()&&(this.element.removeClass("layer-preset-control-selected"),c.Scope.styleEditorForm.hide())},isSelected:function(){return this.element.hasClass("layer-preset-control-selected")},
getData:function(a){a="undefined"===typeof a?!0:a;var b=d.extend(!0,{},this.options);a&&(b.settings.hover=b.hover.allow_style);return b},getName:function(){return this.name},getType:function(){return this.type},getOption:function(a,b){return this.options[void 0===b?"style":b][a]},setOption:function(a,b,c){this.options[void 0===c?"style":c][a]=b},getOptions:function(a,b){a="object"===typeof a?a:{};if("undefined"===typeof b?0:b)a=d.extend(!0,{},this.options,a),d.each(["style","hover"],function(b,f){d.each(a[f],
function(b){c.Vars.preset.options.hasOwnProperty(b)||delete a[f][b]})});else{var f=this.presetList.getStyleMode();a=d.extend(!0,{},this.options[f],a);d.each(a,function(b){c.Vars.preset.options.hasOwnProperty(b)||delete a[b]})}return a},setOptions:function(a,b,c){c="undefined"===typeof c?!1:c;("undefined"===typeof b?0:b)?this.options=a:(b=this.presetList.getStyleMode(),this.options[b]=a);this.options.settings.hover=this.options.hover.allow_style;c||this.render()},render:function(){var a=c.Scope.workground.getCurrent();
if(a){var b=this.getType()===c.LayerPreset.PRIVATE;this.presetList.styleSettings.preview.update(this.getOptions({},!0),b?a.options.private_preset_class:this.getName(),!0,b)}},getLabel:function(){var a=this.options.settings.label;return a?a:c.Vars.lang.layer_preset_private_name},updateLabel:function(a){this.options.settings.label=a;this.lableEl.text(a);can.trigger(this.presetList.element,"presetUpdate",{name:this.getName(),label:a,preset:this})},linkPresetList:function(a){this.presetList=a},scrollToElement:function(){this.presetList.element.animate({scrollTop:this.presetList.element.scrollTop()+
this.element.position().top-this.presetList.element.position().top-this.presetList.element.height()/2+this.element.height()/2},100)}})})(jQuery,MPSL);
(function(d,c){c.StyleEditorModeSwitcher=can.Control.extend({mode:"style",NORMAL_MODE:"style",HOVER_MODE:"hover"},{buttons:{},init:function(a){c.Scope.styleModeSwitcher=this;a.buttonset();this.buttons=this.element.children("input")},"> input change":function(a){a=a.data("mode");c.StyleEditorModeSwitcher.mode=a;can.trigger(this,"switch",a)},getMode:function(){return c.StyleEditorModeSwitcher.mode},setMode:function(a){this.buttons.removeAttr("checked");this.element.children('[data-mode="'+a+'"]').click()},
isMode:function(a){return a===this.getMode()}})})(jQuery,MPSL);
(function(d,c){c.LayerStylePreview=can.Control.extend({},{preview:{},bgToggle:{},bgToggleState:!1,stylesWrapper:{},init:function(a,b){c.Scope.layerStylePreview=this;this.preview=a.children(".mpsl-style-editor-preview");this.bgToggle=a.children(".mpsl-style-editor-bg-toggle");this.stylesWrapper=d("#mpsl-preset-styles-wrapper");c.Functions.disableSelection(this.bgToggle);can.trigger(this.bgToggle,"click",this.bgToggleState)},"> .mpsl-style-editor-bg-toggle click":function(a,b,c){(this.bgToggleState=
"undefined"===typeof c?!this.bgToggleState:c)?(this.element.css("background-color","black"),a.css("background-color","white")):(this.element.css("background-color","white"),a.css("background-color","black"))},update:function(a,b,f,g){a="undefined"===typeof a?[]:a;f="undefined"===typeof f?!1:f;var l,h;g=a.hover.allow_style;var m=a.style.custom_styles;l=a.hover.custom_styles;var n={},k={},p={};delete a.style.allow_style;delete a.style.custom_styles;delete a.hover.allow_style;delete a.hover.custom_styles;
d.each(["style","hover"],function(b,f){d.each(a[f],function(b,g){c.Vars.preset.options[b].isChild?delete a[f][b]:"string"!==typeof g||""===g?delete a[f][b]:(h=c.Vars.preset.options[b].unit,d.isNumeric(g)&&h?a[f][b]=d.trim(g)+h:a[f][b]=d.trim(g),"hover"===f&&-1<d.inArray(b,c.Vars.layout.style_options)&&(a[f][b]+=" !important"))})});d.extend(n,a.style);d.extend(n,this.parseCSS(m));d.extend(p,n);m=this.stringifyCSS(n);d.extend(k,a.hover);d.extend(k,this.parseCSS(l));"hover"===c.StyleEditorModeSwitcher.mode&&
d.extend(p,k);k=this.stringifyCSS(k);d.each(p,function(a,b){p[a]=b.replace("!important","").trim()});this.preview.attr("style","");this.preview.css(p);l=this.preview.attr("style");this.preview.attr("style",l);f&&(l=""+("."+c.Vars.preset.layer_class+"."+b+"{"+m+"}"),g&&(l+="."+c.Vars.preset.layer_class+"."+b+"."+c.Vars.preset.layer_hover_class+"{"+k+"}"),f=d("#"+b),f.length?f.text(l):(f=d("<style>",{type:"text/css","class":"mpsl-preset-style",id:b,text:l}),this.stylesWrapper.append(f)))},parseCSS:function(a){a=
"string"===typeof a?a:"";var b={};a=a.replace(/\/\*.+?\*\//g,"");if(a=d.trim(a))a=a.split(";"),d.each(a,function(c,g){if(g&&(a[c]=g.split(":"),2===a[c].length)){var l=d.trim(a[c][0]),h=d.trim(a[c][1]);l&&h&&(b[l]=h)}});return b},stringifyCSS:function(a){a="object"===typeof a?a:{};var b="";d.each(a,function(a,c){b+=a+":"+c+";"});return b},reset:function(){this.preview.attr("style","")},removeStyles:function(a){a=d("#"+a);a.length&&a.remove()}})})(jQuery,MPSL);
(function(d,c){var a=c.Vars.layout["default"];c.Layout=can.Control.extend({layouts:c.Vars.layout.list,getLayout:function(){return a},setLayout:function(b){a=b}},{init:function(a){c.Scope.Layout=this},change:function(){this.switchLayout(this.element.val())},switchLayout:function(a){this.constructor.setLayout(a);a=this.getWidth();var d=this.getHeight();c.Scope.workground.resizeWorkground(a,d);c.Core.SliderManager.updateGrid(a,d,this.constructor.getLayout());c.Scope.workground.repaintLayers();c.Scope.layerSettingsForm.reinit()},
getWidth:function(){return c.Vars.layout.list[this.constructor.getLayout()].width},getHeight:function(){return c.Vars.layout.list[this.constructor.getLayout()].height}})})(jQuery,MPSL);jQuery(function(d){window.slidePageController=new MPSL.SlidePageController(d(".mpsl-wrapper"))});
